CHK-31 adding support for gene alignments
ENCODE-DCC/checkfiles pull request #19
Opened 2019-03-07 05:47 UTC by gabdank

2019-03-26 19:15 UTC, caseylitton requested changes

2019-03-26 19:15 UTC, caseylitton commented on checkfiles.py
> +    if (item['file_format'] == 'bam' and
May as well use item.get('file_format') == 'bam' and 

the second condition can be a list.  item.get('output_type') in ['trancs..' , 'gene...']

2019-03-26 19:15 UTC, caseylitton commented on checkfiles.py
> +        if item.get('output_type') == 'transcriptome alignments':
Since we're using 'item.get('output_type')' more than once we should put it in a variable.  Above the conditional ~ line 91.

2019-03-26 19:15 UTC, caseylitton commented on checkfiles.py
> +            chromInfo = '-chromInfo=%s/%s/%s/chrom.sizes' % (
These should use .format() not the c-type string creation.  so replace the %s with {} and then the '% (' with .format(

2019-03-26 19:15 UTC, caseylitton commented on checkfiles.py
> +            chromInfo = '-chromInfo=%s/%s/%s/gene.sizes' % (
same here switch to using format.

2019-03-26 19:15 UTC, caseylitton commented on checkfiles.py
>          chromInfo = '-chromInfo=%s/%s/chrom.sizes' % (encValData, assembly)
This one is outside the scope of the feature but if you think it will be QA'd then maybe switch to format here too.

2019-04-09 11:15 UTC, gabdank commented on checkfiles.py
> +    if (item['file_format'] == 'bam' and
fixed

2019-04-09 11:17 UTC, gabdank commented on checkfiles.py
> +        if item.get('output_type') == 'transcriptome alignments':
fixed

2019-04-09 11:19 UTC, gabdank commented on checkfiles.py
> +            chromInfo = '-chromInfo=%s/%s/%s/chrom.sizes' % (
fixed

2019-04-09 11:19 UTC, gabdank commented on checkfiles.py
> +            chromInfo = '-chromInfo=%s/%s/%s/gene.sizes' % (
fixed

2019-04-09 11:19 UTC, gabdank commented on checkfiles.py
>          chromInfo = '-chromInfo=%s/%s/chrom.sizes' % (encValData, assembly)
fixed

2019-04-09 11:24 UTC, gabdank commented
@caseylitton if the current code version passes your code review, could you please switch the Jira ticket into QA ready?

2019-04-09 18:02 UTC, caseylitton approved these changes

2019-04-19 17:08 UTC, merged